module.exports = {
  rules: {
    "array-bracket-newline":  ["error", "consistent"],
    "array-bracket-spacing": "error",
    "array-element-newline": ["error", "consistent"],
    "block-spacing": "error",
    "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
    "camelcase": ["error", { "properties": "never", "ignoreDestructuring": true }],
    // "capitalized-comments": ["error", "always", { "ignoreConsecutiveComments": true }],
    "comma-dangle": ["error", "never"],
    "comma-spacing": "error", 
    "comma-style": "error",
    "computed-property-spacing": "error",
    "consistent-this": ["error", "self"],
    "eol-last": "error",
    "func-call-spacing": "error",
    "func-name-matching": "error",
    // "func-names": "error",
    "func-style": ["error", "declaration", { "allowArrowFunctions": true }],
    "function-paren-newline": ["error", "consistent"],
    // "id-blacklist": "error",
    // "id-length": "error",
    // "id-match": "error",
    "implicit-arrow-linebreak": "error",
    "indent": ["error", 2],
    "jsx-quotes": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    // "line-comment-position": "error",
    "linebreak-style": "error",
    // "lines-around-comment": "error",
    "lines-between-class-members": "error",
    "max-depth": "error",
    "max-len": ["error", { "code": 120 }],
    "max-lines": ["error", { "skipComments": true, "skipBlankLines": true }],
    "max-lines-per-function": ["error", { "skipComments": true, "skipBlankLines": true }],
    "max-nested-callbacks": "error",
    "max-params": ["error", { "max": 5 }],
    "max-statements": ["error", 15, { "ignoreTopLevelFunctions": true }],
    "max-statements-per-line": "error",
    // "multiline-comment-style": "error",
    "multiline-ternary": ["error", "never"],
    "new-cap": ["error", { "properties": false }],
    "new-parens": "error",
    "newline-per-chained-call": ["error", { "ignoreChainWithDepth": 3 }],
    "no-array-constructor": "error",
    "no-bitwise": "error",
    // "no-continue": "error",
    // "no-inline-comments": "error",
    "no-lonely-if": "error",
    // "no-mixed-operators": "error",
    "no-multi-assign": "error",
    "no-multiple-empty-lines": ["error", { "max": 1, "maxBOF": 0, "maxEOF": 1 }],
    "no-negated-condition": "error",
    "no-nested-ternary": "error",
    "no-new-object": "error",
    "no-plusplus": "error",
    // "no-restricted-syntax": "error",
    "no-tabs": "error",
    // "no-ternary": "error",
    "no-trailing-spaces": "error",
    // "no-underscore-dangle": "error",
    "no-unneeded-ternary": "error",
    "no-whitespace-before-property": "error",
    "nonblock-statement-body-position": "error",
    "object-curly-newline": ["error", {
      "ObjectExpression": { "consistent": true },
      "ObjectPattern": { "consistent": true },
      "ImportDeclaration": { "multiline": true },
      "ExportDeclaration": { "multiline": true, "minProperties": 3 }
    }],
    "object-curly-spacing": ["error", "always"],
    // "object-property-newline": "error",
    "one-var": ["error", "never"],
    "one-var-declaration-per-line": "error",
    "operator-assignment": "error",
    "operator-linebreak": ["error", "after"],
    "padded-blocks": ["error", "never"],
    "padding-line-between-statements": ["error",
      { "blankLine": "always", "prev": "*", "next": "return" },
      { "blankLine": "always", "prev": "block-like", "next": "*" },
      
      { "blankLine": "always", "prev": "expression", "next": "*" },
      { "blankLine": "any", "prev": "expression", "next": "expression" },
      
      { "blankLine": "always", "prev": ["const", "let", "var"], "next": "*"},
      { "blankLine": "any", "prev": ["const", "let", "var"], "next": ["const", "let", "var"]},
      
      { "blankLine": "always", "prev": "directive", "next": "*" },
      { "blankLine": "any",    "prev": "directive", "next": "directive" },

      { "blankLine": "always", "prev": ["multiline-const", "multiline-let", "multiline-var"], "next": "*"},
      { "blankLine": "always", "prev": ["multiline-expression", "multiline-block-like"], "next": "*" }
    ],
    "prefer-object-spread": "error",
    "quote-props": ["error", "as-needed"],
    "quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": true }],
    "semi": "error",
    "semi-spacing": "error",
    "semi-style": "error",
    // "sort-keys": "error",
    // "sort-vars": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", "never"],
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": "error",
    "switch-colon-spacing": "error",
    "template-tag-spacing": "error",
    "unicode-bom": "error",
    "wrap-regex": "error"
  }
}